docs(Java): Remove file listings: they are error prone and outdated
cap-js/docs pull request #1009
Opened 2024-06-13 14:07 UTC by bugwelle

In previous commits, I've adapted a few file listings as they were outdated.  This commit removes a few of them, as they don't have any benefit and are rather confusing if we ever change the initial file layout again (e.g. rename `schema.cds` to `cds-model.cds` or similar).

2024-06-26 08:47 UTC, rjayasinghe commented on java/getting-started.md
> +│  └─ …
maybe a place holder like `<your db related cds files>`

2024-06-26 08:47 UTC, rjayasinghe commented on java/getting-started.md
> +   ├─ …
maybe a place holder like `<your db related cds files>`

2024-06-26 08:47 UTC, rjayasinghe commented on java/getting-started.md
> +| *srv/src/gen/java* | Contains the compiled CDS model and generated [accessor interfaces for typed access](./cds-data#typed-access) after building the project once. |
After building the project once with `mvn compile`. Because building it with IDE build support (e.g. CMD+F9 in IntelliJ) would not generate the accessor interfaces.

2024-06-26 08:58 UTC, bugwelle commented on java/getting-started.md
> +│  └─ …
What about just leaving it empty? I think that may be cleaner. :)

```suggestion
```

2024-06-26 08:58 UTC, bugwelle commented on java/getting-started.md
> +   ├─ …
```suggestion
```

2024-06-26 08:58 UTC, bugwelle commented on java/getting-started.md
>  | *srv/src/main/java* | Contains Java application logic. |
```suggestion
| *srv/src/main/java* | Contains Java application logic. It contains a Maven project. |
```

2024-06-26 08:58 UTC, bugwelle commented on java/getting-started.md
> +| *srv/src/gen/java* | Contains the compiled CDS model and generated [accessor interfaces for typed access](./cds-data#typed-access) after building the project once. |
```suggestion
| *srv/src/gen/java* | Contains the compiled CDS model and generated [accessor interfaces for typed access](./cds-data#typed-access) after building the project with `mvn compile` once. |
```

2024-06-26 10:05 UTC, rjayasinghe approved these changes

2024-06-27 08:43 UTC, renejeglinsky approved these changes

2024-06-27 09:53 UTC, rjayasinghe requested changes

2024-06-27 09:53 UTC, rjayasinghe commented on java/getting-started.md
> +| *srv/src/main/java* | Contains Java application logic. It contains a Maven project. |
Please change this to "Contains the Java source code of the `srv` Maven project.

2024-06-27 10:00 UTC, bugwelle commented on java/getting-started.md
> +| *srv/src/main/java* | Contains Java application logic. It contains a Maven project. |
```suggestion
| *srv/src/main/java* | Contains Java application logic. Contains the Java source code of the `srv/` Maven project. |
```

Indeed, this is better. :)

2024-06-27 10:01 UTC, bugwelle commented on java/getting-started.md
> +| *srv/src/main/java* | Contains Java application logic. Contains the Java source code of the `srv/` Maven project. |
```suggestion
| *srv/src/main/java* | Contains the Java source code of the `srv/` Maven project. |
```

2024-06-28 06:47 UTC, renejeglinsky commented
I think Robins requested change is done and it's safe to merge. If needed we can make changes in a new PR.

2024-06-28 06:47 UTC, merged