SAP Document Management Service Plugin Documentation
cap-js/docs pull request #1034
Opened 2024-06-19 08:06 UTC by rashmiangadi11

Adding the documentation for SAP Document Management Service plugin

2024-06-19 13:12 UTC, smahati requested changes

2024-06-19 13:12 UTC, smahati commented on plugins/index.md
> +It also provides a CAP-level, easy-to-use integration of the [SAP Document Management Service](https://help.sap.com/docs/document-management-service).
```suggestion
```

2024-06-19 13:12 UTC, smahati commented on plugins/index.md
> +- Automatic handling of all upload,download,delete and rename operations
```suggestion
- Automatic handling of all operations including upload, download, delete, and rename
```

2024-06-19 13:12 UTC, smahati commented on plugins/index.md
> +- SAP Document Management Service has inbuilt virus scanning feature.
```suggestion
- SAP Document Management Service has a built in virus scanning feature.
```

2024-06-19 13:12 UTC, smahati commented on plugins/index.md
> +- Multitenancy intrinsically handled by the plugin
```suggestion
- Intrinsic multitenancy handling
```

2024-06-19 13:12 UTC, smahati commented on plugins/index.md
> +Outlook:
```suggestion
Future enhancements:
```

2024-06-20 05:25 UTC, rashmiangadi11 commented on plugins/index.md
> +Outlook:
is it mandatory to add enhancements or can be skipped

2024-06-20 11:57 UTC, smahati approved these changes

2024-06-20 11:57 UTC, merged