[3.0] IAS support in Remote Services and IAS migration guide
cap-js/docs pull request #1047
Opened 2024-06-21 11:18 UTC by StefanHenke

2024-06-21 12:10 UTC, beckermarc commented on java/cqn-services/remote-services.md
> +Remote APIs which require IAS-based authentication might expect a certificate based client authentication in addition to the IAS-based JWT token (ie. [proof-of-possession](https://github.com/SAP/clou
```suggestion
Remote APIs which require IAS-based authentication might expect a certificate based client authentication in addition to the IAS-based JWT token (ie. [proof-of-possession](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#proofofpossession-validation)). 
```

2024-06-21 12:10 UTC, beckermarc commented on java/cqn-services/remote-services.md
> +        cloudsdk.ias-dependency-name: <name-of-the-ias-dependency>
```suggestion
url: <url-of-the-remote-api>
authentication-type: None
additional property:
  cloudsdk.ias-dependency-name: <name-of-the-ias-dependency>
```

One might think that this is a configuration file you need to place somewhere. Maybe rather use a bullet point list?

2024-06-21 12:10 UTC, beckermarc commented on java/migration.md
> +In IAS scenarios, the [proof-of-possession](https://github.com/SAP/cloud-security-services-integration-library/tree/629aef6f54cf0b9e41453eb32082a889c16b22d3/java-security#proofofpossession-validation
```suggestion
In IAS scenarios, the [proof-of-possession](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#proofofpossession-validation) is now enforced by default for incoming requests. It is recommended to use at least version `3.5.1` of the [SAP BTP Spring Security Client](https://github.com/SAP/cloud-security-services-integration-library/tree/main/spring-security) library in this case.
```

2024-06-21 12:10 UTC, beckermarc commented on java/migration.md
> +### Proof-Of-Possession enforced for IAS-based authentication
Should this kind of information be rather in our general security guide and only linked from here? This might also be valuable information for stakeholders starting to use IAS after migrating to CAP Java 3.

2024-06-24 08:11 UTC, BraunMatthias approved these changes

2024-06-24 08:23 UTC, StefanHenke commented on java/migration.md
> +### Proof-Of-Possession enforced for IAS-based authentication
Makes sense. I created a sub-chapter (unfortunately on 4th hierarchy level) in the java security guide. I haven´t moved it to the concept security guide as this is at the moment only supported by CAP Java

@BraunMatthias : Could you comment if this is okay for you?

2024-06-24 08:56 UTC, beckermarc commented on java/cqn-services/remote-services.md
> +url: <url-of-the-remote-api>
Maybe better structure this as a bullet point list?

2024-06-24 12:07 UTC, beckermarc commented on java/cqn-services/remote-services.md
> +  - `cloudsdk.ias-dependency-name`: <name-of-the-ias-dependency>
Let's use the same terminology as in the Destinations UI of BTP Cockpit

```suggestion
- URL: <url-of-the-remote-api>
- Authentication: NoAuthentication
- Additional Properties:
  - `cloudsdk.ias-dependency-name`: <name-of-the-ias-dependency>
```

2024-06-24 13:05 UTC, beckermarc approved these changes

2024-06-24 13:41 UTC, smahati commented on java/security.md
> +You can disable the Proof-Of-Possession enforcement in your CAP Java application by setting the property `sap.spring.security.identity.prooftoken` to `false` in the `application.yaml`.
```suggestion
You can disable the Proof-Of-Possession enforcement in your CAP Java application by setting the property `sap.spring.security.identity.prooftoken` to `false` in the `application.yaml` file.
```

2024-06-25 09:11 UTC, BraunMatthias approved these changes

2024-06-25 09:27 UTC, smahati commented on java/cqn-services/remote-services.md
> +```yaml
some part of this block needs to be made into a code block to work. I'm checking.

2024-06-25 09:29 UTC, smahati requested changes

2024-06-25 09:29 UTC, smahati commented on java/cqn-services/remote-services.md
> +```yaml
a part of this needs to be in a code block, I'm checking.

2024-06-25 09:52 UTC, beckermarc commented on java/cqn-services/remote-services.md
> +```yaml
Most likely the <> characters make problems..

2024-06-25 11:29 UTC, smahati commented on java/cqn-services/remote-services.md
> +```yaml
yep, escaping with a backslash or using backticks fixes it. :)

2024-06-25 12:32 UTC, smahati approved these changes

2024-06-25 12:32 UTC, merged