Java plugin docu
cap-js/docs pull request #524
Opened 2023-11-07 15:52 UTC by rjayasinghe

2023-11-16 14:47 UTC, dimamost commented on java/plugin_concept.md
> +Inside your reuse module you can define a custom event handler and and a registration hook as plain Java code. Once this module is addded to any CAP Java application as a dependency the contained eve
typo  -> and and

2023-11-16 14:47 UTC, dimamost commented on java/plugin_concept.md
> +So, in order to have a framework independent handler registration the `` interface needs to be implemented like this:
Which interface? -> ''

2023-11-21 15:58 UTC, rjayasinghe commented on java/plugin_concept.md
> +So, in order to have a framework independent handler registration the `` interface needs to be implemented like this:
fixed

2023-11-21 15:58 UTC, rjayasinghe commented on java/plugin_concept.md
> +In CAP Java, the protocol adapter is the mechanism to implement inbound communication (another service or the UI) to the CAP service in development. The task of a protocol adapter is to translate any
HCQL is a valid abbreviation in CAP Java

2023-11-21 15:59 UTC, rjayasinghe commented on java/plugin_concept.md
> +This technique can be used indepently or together with one or more of the techniques described on this page.
fixed

2023-11-24 09:41 UTC, dimamost approved these changes

2023-11-24 10:53 UTC, rjayasinghe commented
@renejeglinsky all checks passed, a menu entry is created and we have approval from the Java side.

This guide is not documenting a feature from the recent release but concepts and extension points that have been part of CAP Java for a while now.

2023-11-24 11:05 UTC, beckermarc reviewed
Some additional comments from my side :)

2023-11-24 11:05 UTC, beckermarc commented on java/plugin_concept.md
> +Besides extending the capabilities for inbound requests it is also possible to extend the behaviour of event handling during request handling of the CAP Java runtime. Meaning that you can define cust
Where is the difference between "capabilities of inbound requests" and "behaviour of event handling during request handling"?

2023-11-24 11:05 UTC, beckermarc commented on java/plugin_concept.md
> +The real difference to your typical event handler in your application code is the actual handler registration code. Although you could use the same `@Componenent` Spring Framework mechanism this is n
We should probably explain both approaches: The Spring approach is valid, if you need integration with Spring, e.g. due to dependency injection of some other beans provided by another common Spring-based library. This is a common approach and we are often asked to do the auto-configuration in that case (people don't know about Spring Boots auto-configuration mechanisms and usually fallback to extending the classpath scan in the applications).

2023-11-24 11:05 UTC, beckermarc commented on java/plugin_concept.md
> +	public CdsHcqlServlet(CdsRuntime runtime) {
```suggestion
	public SampleAdapter(CdsRuntime runtime) {
```

2023-11-24 18:05 UTC, rjayasinghe commented on java/plugin_concept.md
> +> Note that the location syntax differs from the usual syntax and adheres to the groupId/artifactId syntax defined above. Also, the [CDS editor](../tools/#cds-editor) does not yet support this new lo
provided a new version of that section with the latest commit

2023-11-24 18:08 UTC, rjayasinghe commented on java/plugin_concept.md
> +> Please be ware that the module that uses the reuse module needs to be a Maven module itself or a submodule to a Maven module that declares the dependency to the Maven module. Usually you would decl
fixed

2023-11-24 18:44 UTC, rjayasinghe commented on java/plugin_concept.md
> +Besides extending the capabilities for inbound requests it is also possible to extend the behaviour of event handling during request handling of the CAP Java runtime. Meaning that you can define cust
Reworked the whole section a bit. The start of this section was based on a different ordering in the guide.

2023-11-27 10:10 UTC, t-bonk requested changes
Please add a remark, that the groupId `com.sap.cds` shall not be used by 3rd party plugins, adapters etc.

2023-11-30 13:22 UTC, rjayasinghe commented on java/plugin_concept.md
> +The decision between the two is pretty straightforward: In case your handler depdends on other Spring components e.g. relies on dependency injection you should use the the [Spring approach](#spring-a
fixed

2023-11-30 13:22 UTC, rjayasinghe commented
> Please add a remark, that the groupId `com.sap.cds` shall not be used by 3rd party plugins, adapters etc.

fixed!

2023-12-07 10:32 UTC, rjayasinghe commented
> Please add a remark, that the groupId `com.sap.cds` shall not be used by 3rd party plugins, adapters etc.

I added a section for that.

2023-12-07 12:03 UTC, t-bonk approved these changes
LGTM

2023-12-11 10:22 UTC, renejeglinsky commented
Should I rename the file from plugin-concept to just plugins? Or sth else?

2023-12-11 10:30 UTC, renejeglinsky commented on java/plugin_concept.md
> +When building CAP Java plugin modules you need to keep in mind that the generated Java byte code of the plugin has to be compatible with the Java byte code version of the potential consumers of the p
Could it be an option to build the plugin for several versions? Or is this usually not feasible?

2023-12-11 10:33 UTC, renejeglinsky commented on java/plugin_concept.md
> +Of course it's up to your project / plugin how you call the corresponding Maven GroupId and Java packages. In order to avoid confusion and also to make responsibilities clear `com.sap.cds` for GroupI
Is this targeted towards an SAP-internal audience?

2023-12-11 10:36 UTC, t-bonk commented on java/plugin_concept.md
> +Of course it's up to your project / plugin how you call the corresponding Maven GroupId and Java packages. In order to avoid confusion and also to make responsibilities clear `com.sap.cds` for GroupI
@renejeglinsky @rjayasinghe In my opinion this is targeted to all audiences, no matter whether they're internal or external.

2023-12-12 17:46 UTC, rjayasinghe commented on java/plugin_concept.md
> +When building CAP Java plugin modules you need to keep in mind that the generated Java byte code of the plugin has to be compatible with the Java byte code version of the potential consumers of the p
Not really, at the moment we need to define the cds-services as well as the JDK version fixed. This works for sure. For anything else we need some more thinking.

2023-12-13 06:11 UTC, renejeglinsky commented on java/plugin_concept.md
> +Projects wanting to import the content simply add a Maven dependency to the reuse package to their `pom.xml` in the `<dependencies>` section.
Do I consume that, until this point locally? If yes, I guess the location of the new artifact is in parallel to my CAP project, as it is also for Node.js, right?
Or do we need a "Publish to Maven" step in between this and the previous step?

2023-12-13 07:11 UTC, renejeglinsky commented on java/plugin_concept.md
> +In CAP Java, the protocol adapter is the mechanism to implement inbound communication (another service or the UI) to the CAP service in development. The task of a protocol adapter is to translate any
How about shortening this intro and link to https://cap.cloud.sap/docs/java/architecture#protocol-adapters? This chapter about protocol adapters would need an update then, I guess?

2023-12-13 09:38 UTC, renejeglinsky commented
Will merge this and go over some points with Robin later.

2023-12-13 09:38 UTC, renejeglinsky approved these changes

2023-12-13 09:56 UTC, merged