CDS4j: Update with expressions
cap-js/docs pull request #591
Opened 2023-12-15 14:01 UTC by MattSchur

2023-12-15 15:25 UTC, agoerler approved these changes
Looks good to me. A minor suggestion only.

2023-12-15 15:25 UTC, agoerler commented on java/query-api.md
> +In addition to the update data with plain Java values, you can also update with CQL expressions via the `set` method, e.g. to decrease the stock of Book 101 by 1:
```suggestion
The [data](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#data(java.util.Map)), [entry](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#entry(java.util.Map)), and  [entries](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#entries(java.lang.Iterable)) methods allow to specify the new values as plain Java values. In addition or alternatively you can use the `set` method to specify the new value as a `CqnValue`, which can even be an expression. This allows, for example, to decrease the stock of Book 101 by 1:
```

2023-12-16 10:09 UTC, agoerler requested changes
We also need to document that the setter expressions are evaluated on the DB and the result of the expressions is not available in the `Result` of the execution of the `Update`.

The application might have to read after write in custom code.

2023-12-16 14:14 UTC, agoerler commented
> Document result of update with expressions

https://github.com/cap-js/docs/pull/591/commits/6de14aede3f83b9bece0398175fe59f61dd2bc70

2023-12-16 14:15 UTC, agoerler approved these changes

2023-12-18 08:11 UTC, renejeglinsky commented on java/query-api.md
> +The [data](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#data(java.util.Map)), [entry](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#
Can we add a capire link for CqnValue?

2023-12-18 09:29 UTC, agoerler commented on java/query-api.md
> +The [data](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#data(java.util.Map)), [entry](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#
```suggestion
The [data](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#data(java.util.Map)), [entry](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#entry(java.util.Map)), and  [entries](https://javadoc.io/doc/com.sap.cds/cds4j-api/latest/com/sap/cds/ql/Update.html#entries(java.lang.Iterable)) methods allow to specify the new values as plain Java values. In addition/alternatively you can use the `set` method to specify the new [value](#values) as a `CqnValue`, which can even be an expression. This allows, for example, to decrease the stock of Book 101 by 1:
```

2023-12-18 10:40 UTC, renejeglinsky approved these changes
Thanks!

2023-12-18 10:40 UTC, merged