Document fluent style of typed access interfaces
cap-js/docs pull request #626
Opened 2024-01-15 11:41 UTC by vmikhailenko

Document and showcase fluent interface style for CAP Java

2024-01-15 12:36 UTC, mofterdinger commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the [CDS Maven Plugin](./advanced#staticmodel) and affects all entities and event contexts in your services. The generation mode d
Do you want to point to the `cds-maven-plugin` documentation to the goal `generate` ? Then, I think the link is wrong.

2024-01-15 14:57 UTC, vmikhailenko commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the [CDS Maven Plugin](./advanced#staticmodel) and affects all entities and event contexts in your services. The generation mode d
I added the direct link. I wonder how to test that it works..

2024-01-15 15:05 UTC, mofterdinger commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the [CDS Maven Plugin](./advanced#staticmodel) and affects all entities and event contexts in your services. The generation mode d
Maybe locally with this capire dev. server setup.

2024-01-15 15:06 UTC, mofterdinger commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the [CDS Maven Plugin](./advanced#staticmodel) and affects all entities and event contexts in your services. The generation mode d
see: https://github.com/cap-js/docs#running-locally

2024-01-15 15:37 UTC, vmikhailenko commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the goal [cds:generate](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the CDS Maven Plugin and affects all ent
They seem to be checked in the end. https://github.com/cap-js/docs/actions/runs/7530987932/job/20498548492?pr=626

With `../assets` the path looks wrong even in the browser.

2024-01-15 15:56 UTC, mofterdinger commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the goal [cds:generate](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the CDS Maven Plugin and affects all ent
mhh, strange, that's what I found in the existing docu.

2024-01-15 15:57 UTC, mofterdinger commented on java/data.md
> +The generation mode is configured by the property `<methodStyle>` of the goal [cds:generate](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the CDS Maven Plugin and affects all ent
can try without the anchor #methodstyle ?

2024-01-16 08:30 UTC, vmikhailenko commented on java/data.md
> +If you use the fluent style generation and have a custom action or a function in your service, you have to explicitly set the event context as completed by explicitly calling the method `setCompleted
Something like that. I stumbled upon this while playing and we do the same in our sample here https://github.com/SAP-samples/cap-sflight/blob/c868b1c1f7ebf7fbc58ceacce3335b0d4ec964cc/srv/src/main/java/com/sap/cap/sflight/processor/DeductDiscountHandler.java#L67

Thought that it is worth mentioning.

2024-01-16 08:46 UTC, mofterdinger commented on java/data.md
> +If you use the fluent style generation and have a custom action or a function in your service, you have to explicitly set the event context as completed by explicitly calling the method `setCompleted
Ok, thanks for pointing me to the current implementation. Once we have fixed / changed the implementation we can adjust this documentation again.

2024-01-16 08:46 UTC, mofterdinger approved these changes

2024-01-16 13:03 UTC, vmikhailenko commented on java/data.md
> +If you use the fluent style generation and have a custom action or a function in your service, you have to explicitly set the event context as completed by explicitly calling the method `setCompleted
We fixed this. I could retain the warning with release-specific clause or we could merge this after 2.6.0 and omit it.

2024-01-16 15:37 UTC, agoerler requested changes

2024-01-16 15:37 UTC, agoerler commented on java/data.md
> +By default, the accessor interfaces are generated so that the properties of an entity can be read and changed with the getter and the setter methods that mimic the Java Bean API or a way the properti
```suggestion
By default, the accessor interfaces are generated so that the elements of an entity are accessed by getter and the setter methods that follow the design pattern for properties of the [JavaBeans specification](https://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/) (8.3) as commonly used  by other ORM frameworks.
```

2024-01-16 15:37 UTC, agoerler commented on java/data.md
> +Following is the example of the interface generated with the default style:
```suggestion
Following is the example uses accessor interfaces that have generated with the default style:
```

2024-01-16 15:37 UTC, agoerler commented on java/data.md
> +You can also generate accessor interfaces in the style of the _Fluent Interface_ pattern. In this mode, the getter methods are named after the property names and the setter methods return the accesso
```suggestion
Alternatively, you can generate accessor interfaces in _fluent style_: In this mode, the read methods are named after the property names. The write methods return the accessor interface itself to enable chained calls. 
```

2024-01-16 15:37 UTC, agoerler commented on java/data.md
> +The generation mode is configured by the property [`<methodStyle>`](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the goal `cds:generate` of the CDS Maven Plugin and affects all e
```suggestion
The generation mode is configured by the property [`<methodStyle>`](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the goal `cds:generate` of the CDS Maven Plugin and affects all entities and event contexts in your services. The generation mode does not affect the way how the query [model interfaces](../java/advanced#model-interfaces) of the [static model](../java/advanced#static-model-in-the-query-builder) for the query builder. The event contexts and accessor interfaces delivered by the CAP itself always follow the JavaBeans style.
```

2024-01-16 15:37 UTC, agoerler commented on java/data.md
> +   Books.create().author(authors).title("Wuthering Heights");
```suggestion
   Authors author = Authors.create().name("Emily Brontë");
   Books.create().author(author).title("Wuthering Heights");
```

2024-01-16 15:37 UTC, agoerler commented on java/data.md
> +    books.setTitle("Wuthering Heights");
```suggestion
    Authors author = Authors.create();
    author.setName("Emily Brontë");
	
    Books book = Books.create();
    book.setAuthor(authors);
    book.setTitle("Wuthering Heights");
```

2024-01-16 15:45 UTC, vmikhailenko commented on java/data.md
> +The generation mode is configured by the property [`<methodStyle>`](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the goal `cds:generate` of the CDS Maven Plugin and affects all e
Not sure if that phrase is better. I wanted to say that the difference in style does not influence the way the framework works. That this style is the matter of taste.

2024-01-16 15:49 UTC, vmikhailenko commented on java/data.md
> +By default, the accessor interfaces are generated so that the properties of an entity can be read and changed with the getter and the setter methods that mimic the Java Bean API or a way the properti
Why mention the spec at all? We can say something like "classic" or "familiar to seasoned Java developers".

2024-01-16 16:02 UTC, agoerler commented on java/data.md
> +The generation mode is configured by the property [`<methodStyle>`](./assets/cds-maven-plugin-site/generate-mojo.html#methodstyle) of the goal `cds:generate` of the CDS Maven Plugin and affects all e
Aha. I thought you wanted to say that the style does not affect how the "builder interfaces" (model interfaces) are generated. So we want to document:

* style of accessor interfaces is a question of personal taste
* the CAP Java runtime does not care
* model interfaces are not affected

2024-01-16 16:09 UTC, agoerler commented
We should also mention the property name `BEAN` (default) somewhere: https://pages.github.tools.sap/cap/docs/java/assets/cds-maven-plugin-site/generate-mojo.html#methodstyle

2024-01-16 16:46 UTC, agoerler commented on java/data.md
> +By default, the accessor interfaces prodive the setter and getter methods inspired by the JavaBeans specification and the way used by the common ORM frameworks.
```suggestion
By default, the accessor interfaces provide the setter and getter methods inspired by the JavaBeans specification and the way used by the common ORM frameworks.
```

2024-01-16 16:46 UTC, agoerler commented on java/data.md
> +The way the interfaces are generated does not affect how the entities represented by them are handled by CAP and does not change the way how the event contexts and entities delivered by the CAP looks
```suggestion
The way the interfaces are generated determines only how data is accessed by custom code. It does not affect how the data is represented in memory and handled by the CAP Java runtime. 

Moreover, it does not change the way how the event contexts and entities delivered by the CAP looks like. Such interfaces from CAP are always modelled in the default JavaBeans style.
```

2024-01-16 17:36 UTC, agoerler approved these changes

2024-01-19 08:31 UTC, agoerler commented on java/data.md
> +The style of the interfaces depends on your preference. Select the one that is best for you.
That's not an individual preference. You would have to agree within your team which style should be used within your application.

2024-01-19 08:36 UTC, vmikhailenko commented on java/data.md
> +By default, the accessor interfaces provide the setter and getter methods inspired by the JavaBeans specification and the way used by the common ORM frameworks.
I am trying to say that by default the way objects look like is familiar to the seasoned Java developer used to JPA.

2024-01-19 08:37 UTC, vmikhailenko commented on java/data.md
> +The style of the interfaces depends on your preference. Select the one that is best for you.
And this is probably the decision you take once per project.

2024-01-19 09:09 UTC, renejeglinsky commented on java/data.md
> +By default, the accessor interfaces provide the setter and getter methods inspired by the JavaBeans specification and the way used by the common ORM frameworks.
Understood. So to keep it simple, we could omit this part, right? We don't really loose information that way, do we?
```suggestion
By default, the accessor interfaces provide the setter and getter methods inspired by the JavaBeans specification.
```

2024-01-19 09:11 UTC, renejeglinsky commented on java/data.md
> +The style of the interfaces depends on your preference. Select the one that is best for you.
Is this then a recommendation we want to give here? Or is this sth. a team anyways knows and agrees upon project start? If we want to give that recommendation, we can use a green box and spent one or two sentences on that to cover all aspects.

2024-01-23 09:16 UTC, vmikhailenko commented on java/data.md
> +The style of the interfaces depends on your preference. Select the one that is best for you.
Both options are fine, the general recommendation could be that one should stick to the defaults. 

We just wanted to highlight that there is a choice there.

2024-01-24 07:13 UTC, renejeglinsky commented on java/data.md
> +The style of the interfaces depends on your preference. Select the one that is best for you.
```suggestion
Once, when starting a project, select the style of the interfaces that is best for your team and project. We recommend the default JavaBeans style.
```

2024-01-24 11:07 UTC, renejeglinsky approved these changes

2024-01-24 11:14 UTC, merged