Document limitations for Select ... lock()
cap-js/docs pull request #630
Opened 2024-01-15 17:01 UTC by vmikhailenko

Add a summary and some examples of the cases when the `Select` statement with the `lock()` clause does not work.

2024-01-16 15:52 UTC, agoerler requested changes

2024-01-16 15:52 UTC, agoerler commented on java/query-api.md
> +* You cannot use `lock()` and `distinct()` in the same statement.
```suggestion
* You cannot use `lock()` with `distinct()` or `groupBy()`.
```

2024-01-16 15:52 UTC, agoerler commented on java/query-api.md
> +* Localized entities can be locked only if you manually reset the locale via dedicated request context without the locale as described in the chapter [Modifying Request Context](./request-contexts#mo
```suggestion
* Localized entities can be locked only if you the query is executed without a locale as described in the chapter [Modifying Request Context](./request-contexts#modifying-requestcontext). 
```

2024-01-16 15:52 UTC, agoerler commented on java/query-api.md
> +Not every database entity exposed via the CDS entity can be locked with the `lock()` clause. Databases require that the target of such statements is represented by a single table or a view that is ba
```suggestion
Not every entity exposed via the CDS entity can be locked with the `lock()` clause. Databases require that the target of such statements is represented by a single table or by a view that is simple enough so that the database can ambiguously identify which rows must be locked. On views, which are joining multiple tables, which are aggregating data, or which are computing expressions or coalescence of values `lock()` can't be executed. Some databases might have additional restrictions or limitations specific to them.  
```

2024-01-16 17:38 UTC, agoerler approved these changes

2024-01-19 07:56 UTC, renejeglinsky approved these changes

2024-01-22 16:39 UTC, merged