Java occ
cap-js/docs pull request #693
Opened 2024-02-21 18:27 UTC by agoerler

2024-02-22 09:07 UTC, eugene-andreev requested changes
still in review

2024-02-22 09:07 UTC, eugene-andreev commented on java/query-execution.md
> +## Concurreny Control
```suggestion
## Concurrency Control
```

2024-02-22 09:07 UTC, eugene-andreev commented on java/query-execution.md
> +### Optimistic Concurreny Control {#optimistic}
```suggestion
### Optimistic Concurrency Control {#optimistic}
```

2024-02-22 09:07 UTC, eugene-andreev commented on java/query-execution.md
> +Concurreny control allows to protect your data against unexpected concurrent changes.
```suggestion
Concurrency control allows to protect your data against unexpected concurrent changes.
```

2024-02-22 09:07 UTC, eugene-andreev commented on java/query-execution.md
> +An ETag can also be used programatically in custom code. Use the `CqnEtagPredicate` to specify the expected ETag values in an update or delete operation. You can create an ETag predicate using the `C
```suggestion
An ETag can also be used programmatically in custom code. Use the `CqnEtagPredicate` to specify the expected ETag values in an update or delete operation. You can create an ETag predicate using the `CQL.etag` or the `StructuredType.etag` methods.
```

2024-02-22 09:07 UTC, eugene-andreev commented on java/query-execution.md
> +It is also possible, but not recommend, that the new ETag value is provided by custom code in a `@Before`-update handler.
```suggestion
It is also possible, but not recommended, that the new ETag value is provided by custom code in a `@Before`-update handler.
```

2024-02-22 09:07 UTC, eugene-andreev commented on java/query-execution.md
> +If an ETag element is annotated `@cds.on.update` and custom code explicitly sets a value for this element the runtime will _not_ generated a new value upon update but the value, which comes from the
```suggestion
If an ETag element is annotated `@cds.on.update` and custom code explicitly sets a value for this element the runtime will _not_ generate a new value upon update but the value, which comes from the custom code will be used.
```

2024-02-22 09:17 UTC, eugene-andreev commented on java/query-execution.md
> +CAP Java also to store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element wi
```suggestion
CAP Java also to store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with `@cds.java.version` to advise the runtime to manage its value.
```

2024-02-22 09:17 UTC, eugene-andreev commented on java/query-execution.md
> +Version elements can be used with an [ETag predicate](#etag-predicate) to programatically check an expected ETag value. Moreover, if additionally annotated with `@odata.etag`, they can be for [confli
```suggestion
Version elements can be used with an [ETag predicate](#etag-predicate) to programmatically check an expected ETag value. Moreover, if additionally annotated with `@odata.etag`, they can be for [conflict detection](../guides/providing-services#etag) in OData.
```

2024-02-22 09:17 UTC, eugene-andreev commented on java/query-execution.md
> +If the update data contains a value for a version element this values is used as the _expected_ value for the version. This allows to very conveniently use version elements in programatic flow:
```suggestion
If the update data contains a value for a version element this values is used as the _expected_ value for the version. This allows to use version elements in programmatic flow conveniently:
```

2024-02-22 09:35 UTC, eugene-andreev commented on java/query-execution.md
> +No ETag checks are execute when an upsert is executed.
```suggestion
No ETag checks are executed when an upsert is executed.
```

2024-02-22 11:10 UTC, beckermarc commented on java/query-api.md
> +You can also use the `etag` methods of the `CQL` interface to construct an ETag predicate in [tree style](#cql-helper-interface):
```suggestion
You can also use the `eTag` methods of the `CQL` interface to construct an ETag predicate in [tree style](#cql-helper-interface):
```

And also in other occurrences

2024-02-22 11:10 UTC, beckermarc commented on java/query-execution.md
> +In the [OData protocol](../guides/providing-services#etag), the implementation relies on `ETags` and `If-Match` headers in the HTTP request.
```suggestion
In the [OData protocol](../guides/providing-services#etag), the implementation relies on `ETag` and `If-Match` headers in the HTTP request. 
```

2024-02-26 08:10 UTC, eugene-andreev approved these changes
lgtm

2024-02-26 09:02 UTC, beckermarc commented on java/query-execution.md
> +CAP Java also to store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element wi
```suggestion
CAP Java also supports to store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with `@cds.java.version` to advise the runtime to manage its value.
```

2024-02-26 09:02 UTC, beckermarc commented on java/query-execution.md
> +Version elements can be used with an [ETag predicate](#etag-predicate) to programmatically check an expected ETag value. Moreover, if additionally annotated with `@odata.etag`, they can be for [confl
```suggestion
Version elements can be used with an [ETag predicate](#etag-predicate) to programmatically check an expected ETag value. Moreover, if additionally annotated with `@odata.etag`, they are used for [conflict detection](../guides/providing-services#etag) in OData.
```

2024-02-26 09:28 UTC, renejeglinsky commented on java/query-execution.md
> +No exception is thrown if an ETag validation does not match but the execution of the update (or delete) will succeed. Instead, the application has to check the `rowCount` of the `Result`. The value 0
Is my understanding correct?
If ETag validation fails, the update operation succeeds but doesn't change any data. Instead the application has to check if an update was successful by checking the `rowCount`. 
Right? And in that case? I guess my custom code should throw an exception then or output a warning or sth alike, right?

2024-02-26 16:28 UTC, agoerler commented on java/query-execution.md
> +CAP Java also stores ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with
```suggestion
CAP Java also allows to store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with `@cds.java.version` to advise the runtime to manage its value.
```

2024-02-26 16:28 UTC, agoerler commented on java/query-execution.md
> +Additionally, to elements of type `Timestamp` and `UUID`, `@cds.java.version` supports all integral types `Uint8`, ... `Int64`. For timestamp, the value is set to `$now` upon update, for elements of
```suggestion
As opposed to `@cds.on.update`, which allows for ETag elements with type `Timestamp` or `UUID` only, `@cds.java.version` additionally supports all integral types `Uint8`, ... `Int64`. For timestamp, the value is set to `$now` upon update, for elements of type UUID a new UUID is generated, and for elements of integral type the value is incremented.
```

2024-02-26 16:30 UTC, agoerler commented on java/query-execution.md
> -:::warning
I think this warning is quite important. Maybe we should keep it.

2024-02-27 11:04 UTC, renejeglinsky commented on java/query-execution.md
> +No exception is thrown if an ETag validation does not match but the execution of the update (or delete) will succeed. Instead, the application has to check the `rowCount` of the `Result`. The value 0
Is that stating the obvious?
```suggestion
No exception is thrown if an ETag validation does not match. Instead, the execution of the update (or delete) succeeds but doesn't apply any changes. Ensure that the application checks the `rowCount` of the `Result` and implement your error handling. If the value of `rowCount` is 0, that indicates that no row was updated (or deleted).
```

2024-02-27 11:06 UTC, renejeglinsky commented on java/query-execution.md
> +CAP Java also stores ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with
```suggestion
You can store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with `@cds.java.version` to advise the runtime to manage its value.
```

2024-02-27 11:08 UTC, renejeglinsky commented on java/query-execution.md
> +Additionally, to elements of type `Timestamp` and `UUID`, `@cds.java.version` supports all integral types `Uint8`, ... `Int64`. For timestamp, the value is set to `$now` upon update, for elements of
```suggestion
Compared to `@cds.on.update`, which allows for ETag elements with type `Timestamp` or `UUID` only, `@cds.java.version` additionally supports all integral types `Uint8`, ... `Int64`. For timestamp, the value is set to `$now` upon update, for elements of type UUID a new UUID is generated, and for elements of integral type the value is incremented.
```

2024-02-27 11:11 UTC, renejeglinsky commented on java/query-execution.md
> -:::warning
This sentence is now in line 287. I think it fits and I also want to avoid two warning boxes following each other.
Do you want to keep it in a warning box?

2024-02-27 11:12 UTC, agoerler commented on java/query-execution.md
> +CAP Java also stores ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with
```suggestion
Alternatively, you can store ETag values in _version elements_. For version elements, the values are exclusively managed by the runtime without the option to set them in custom code. Annotate an element with `@cds.java.version` to advise the runtime to manage its value.
```

2024-02-27 11:26 UTC, renejeglinsky approved these changes

2024-02-27 17:13 UTC, agoerler commented on java/query-execution.md
> -:::warning
We can do without the warning box.

2024-02-27 18:18 UTC, merged