Change tracking in Java
cap-js/docs pull request #712
Opened 2024-02-28 13:33 UTC by vmikhailenko

Locally, the documentation is available in by the direct link http://localhost:5173/docs/java/change-tracking

2024-02-28 13:36 UTC, vmikhailenko commented
Not sure if we want to include the service here.. It is somewhat nasty to write handlers for it as it is hidden by default.

Diff API also ready to be published, I can add something about it here, if needed.

2024-02-28 13:47 UTC, vmikhailenko commented
And maybe, the example with composition: e.g. Order -> Items is needed.

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +  the user interaction and not on the domain level or for data replication.
```suggestion
  the user interaction and not on the domain level (for instance during data replication).
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +- the marker that represents the nature of the change: addition, modification or deletion.
```suggestion
- A marker that represents the nature of the change: addition, modification or deletion.
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +- the new and old values as a strings.
```suggestion
- the new and old values as strings. 
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +- the path that contains the primary keys of the entity and names of the attributes from the root to the target.
```suggestion
- the technical path from the root entity to the tracked target entity.
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +Every modifying operation that is executed via the CQN requires an additional reads to retrieve the old state
```suggestion
Every modifying CQN-based operation requires two additional READ to retrieve the old state 
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +Then they are compared and stored within the change log. Nature of the change is determined by comparing the old and new
```suggestion
The images are compared and differences are stored within the change log. Nature of the change is determined by comparing the old and new 
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +values of the entity: data that were not present in the old values are considered as added, data that are not present in
```suggestion
values of the entity: data that were not present in the old values are considered as added whereas data that are not present in 
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +The change tracking feature tracks the changes of all modifying operations that are executed on the entity via CQN statements,
```suggestion
The feature tracks the changes of all modifying operations executed via CQN statements which are indirectly triggered by adapters or directly by custom code.
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +on the projection level, only the changes made through that projection will be tracked.
```suggestion
on the projection level, only the changes made through that projection is tracked.
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +In case of the `Books` example above, the changes made through the `Books` projection will be tracked, but the changes
```suggestion
In case of the `Books` example above, the changes made through the service entity `Bookshop.Books` are tracked, but the changes
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +made on the domain entity will not be. That can be beneficial if you have a service that is used for data replication
```suggestion
made on the domain entity are omitted. That can be beneficial if you have a service that is used for data replication
```

2024-02-28 17:58 UTC, BraunMatthias commented on java/change-tracking.md
> +When you decide how to annotate your elements, you should consider not only the structure of it but also the way it is changed
I don't understand the intention of this sentence

2024-02-29 08:52 UTC, vmikhailenko commented on java/change-tracking.md
> +You POM also must include the goal to resolve the CDS model delivered from the feature. See [Reference the New CDS Model in an Existing CAP Java Project](./plugins#reference-the-new-cds-model-in-an-e
This is a requirement, not a tip. How about adding a snippet to save people a click?

2024-02-29 09:56 UTC, vmikhailenko commented on java/change-tracking.md
> +When you decide how to annotate your elements, you should consider not only the structure of it but also the way it is changed
What I wanted to say is that with change tracking it is important to know which projections are used to change the data. In custom code it is rather easy to mess with that (names can be very confusing).

2024-03-01 10:26 UTC, beckermarc approved these changes
+1

2024-03-05 22:51 UTC, agoerler reviewed
Please also mention Change Tracking in CAP on the plugins page: plugins/index.md

2024-03-05 23:05 UTC, agoerler requested changes

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +Elements annotated with `@changelog` and which are subject to audit logging, i.e. annotated
```suggestion
Elements annotated with `@changelog` and which are also subject to audit logging, i.e. annotated 
```

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +the elements on the domain level, that means that every change made through every projection of the entity will be tracked.
```suggestion
the elements on the domain level every change made through every projection of the entity will be tracked.
```

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +If you annotate the elements on the projection level, only the changes made through that projection is tracked.
```suggestion
If you annotate the elements on the projection level only the changes made through that projection is tracked.
```

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +The images are compared and differences are stored within the change log. Nature of the change is determined by comparing the old and new
```suggestion
The images are compared and differences are stored in the change log. The nature of the change is determined by comparing the old and new 
```

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +## Detection of changes
```suggestion
## Detection of Changes
```

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +## How change logs are stored?
```suggestion
## How are Change Logs Stored?
```

2024-03-05 23:05 UTC, agoerler commented on java/change-tracking.md
> +## Things to consider when using change tracking
```suggestion
## Things to Consider when Using Change Tracking
```

2024-03-06 10:43 UTC, vmikhailenko commented on java/change-tracking.md
> +Then, you have to **extend the domain entity** with the aspect `changelog.changeTracked` like this:
Technically, yes. Aspect can be anywhere, but it has to be on the first level where the entity wants to see its changes. Having it on the domain level just ensures that the application developer has a choice to move the change log annotations across the projections and not to worry that some changes will lose the references to the entities they belong to.

2024-03-06 10:51 UTC, vmikhailenko commented
> Please also mention Change Tracking in CAP on the plugins page: plugins/index.md

Here? https://cap.cloud.sap/docs/plugins/#change-tracking

Should I just mention that there is a Java version and link the main chapter?

2024-03-06 11:01 UTC, agoerler commented
> Should I just mention that there is a Java version and link the main chapter?

Minimum would be have the Java Icon under "available for" and either link the icon to java or use the "learn more" arrow.

2024-03-06 11:17 UTC, vmikhailenko commented
> > Should I just mention that there is a Java version and link the main chapter?
> 
> Minimum would be have the Java Icon under "available for" and either link the icon to java or use the "learn more" arrow.

I wonder how confusing it is when you see the link on top to Node.js plugin that has nothing to do with Java.

2024-03-06 11:24 UTC, renejeglinsky commented
> * The image should link to our Maven Central dependency page
> * We should have a Learn More link below if applicable
> * The link under the headline should either be removed (Node.js icon points there already) or we should also add the Maven Central dependency link there for Java as well.

- The link under the headline points to npmjs and the icon to the GitHub repo. We could add the Maven Central link also under the headline.
- A learn more link makes sense, as long as there's no GitHub repo. 👍
- The image is then w/o a link

2024-03-06 11:27 UTC, beckermarc commented
> The link under the headline points to npmjs and the icon to the GitHub repo.

Ah I missed this, thanks. Yeah then it makes sense to use the Maven Central link there and just keep the Image without a link in case there is no OpenSource repo. Internally we could link to the respective code, but I don't know how to separate that between external and internal capire.

2024-03-06 11:35 UTC, vmikhailenko commented
It is better to agree on this. Which Maven Central. This one https://central.sonatype.com/artifact/com.sap.cds/cds-feature-change-tracking/2.7.0/overview? 

Also, the audit log has the same "problem".  Telemetry? We also have an implementation.

2024-03-06 11:38 UTC, beckermarc commented
> Which Maven Central. This one https://central.sonatype.com/artifact/com.sap.cds/cds-feature-change-tracking/2.7.0/overview?

Yes, but ideally without the version: https://central.sonatype.com/artifact/com.sap.cds/cds-feature-change-tracking

2024-03-06 11:41 UTC, vmikhailenko commented
For example:
<img width="708" alt="Bildschirmfoto 2024-03-06 um 12 41 12" src="https://github.com/cap-js/docs/assets/5881459/2c72a97f-3215-4cc7-9653-a71e4bb6e79f">

2024-03-06 11:47 UTC, beckermarc commented on plugins/index.md
> +[@cap-js/change-tracking](https://npmjs.com/package/@cap-js/change-tracking) [CAP Java Change Tracking](https://central.sonatype.com/artifact/com.sap.cds/cds-feature-change-tracking) {.subtitle}
I'd also use the dependency name, as for the npm case.

```suggestion
[@cap-js/change-tracking](https://npmjs.com/package/@cap-js/change-tracking) [cds-feature-change-tracking](https://central.sonatype.com/artifact/com.sap.cds/cds-feature-change-tracking) {.subtitle}
```

2024-03-06 11:51 UTC, renejeglinsky commented
> Internally we could link to the respective code in our internal repositories, but I don't know how to separate that between external and internal capire.

Let's skip that and only link public repos that can also handle issues and feature requests etc then

2024-03-07 07:29 UTC, renejeglinsky commented on plugins/index.md
> +Learn more about change tracking in [Java](../java/change-tracking) {.learn-more}
```suggestion
[Learn more about change tracking in Java](../java/change-tracking) {.learn-more}
```

2024-03-14 13:10 UTC, renejeglinsky commented
Is this PR ready or are there open issues/questions?

2024-03-14 13:28 UTC, agoerler commented on java/change-tracking.md
> +The change tracking works around the modifying CQL statements (`Insert`, `Upsert`, `Update`, and `Delete`) and
```suggestion
The change tracking intercepts the modifying CQL statements (`Insert`, `Upsert`, `Update`, and `Delete`) and 
```

2024-03-14 13:40 UTC, agoerler commented
> For example: <img alt="Bildschirmfoto 2024-03-06 um 12 41 12" width="708" src="https://private-user-images.githubusercontent.com/5881459/310480094-2c72a97f-3215-4cc7-9653-a71e4bb6e79f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjM3NTMsIm5iZiI6MTcxMDQyMzQ1MywicGF0aCI6Ii81ODgxNDU5LzMxMDQ4MDA5NC0yYzcyYTk3Zi0zMjE1LTRjYzctOTY1My1hNzFlNGJiNmU3OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTMzNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjMzZWRhNzcwN2E5NDUyMDAwODY1MDRjMDVmMjQ5Njc1MTU3NDZlMzg1MDFjM2UwMDYyYzE1MTk2ZGY1ZGQ4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PV1XbBInzDG4D_kYmucKfrEDv7a6A93Ka2WWhgUe2dI">

Looks good to me. 

@renejeglinsky could we follow this pattern for the other Java "plugins":

* OData v2
* Audit Log
* Telemetry
* DwC
* Kafka

2024-03-14 13:59 UTC, vmikhailenko commented
@renejeglinsky why I see lot of dead link in a PR job?

2024-03-14 14:07 UTC, vmikhailenko commented on java/change-tracking.md
> +These two states are compared and differences are stored in the change log. The nature of the change is determined by comparing the old and new
Probably it is only me, but I do not like `image` in this context. Too technical or too confusing....

2024-03-14 14:11 UTC, agoerler approved these changes
Looks good to me

2024-03-15 08:26 UTC, BraunMatthias approved these changes

2024-03-15 10:56 UTC, renejeglinsky approved these changes

2024-03-15 11:00 UTC, merged