Better Lint documentation
cap-js/docs pull request #756
Opened 2024-03-19 06:39 UTC by mnkiefer

2024-03-20 09:46 UTC, mnkiefer commented
@chgeo: Any idea why the *link* for _assets/native-hana-samples.zip_ is *broken* in the **PR Build (SAP)** pipeline?
```
Found 1 broken link(s) to internal targets in 1 source(s): 
in: /advanced/hana
Not Found (404): assets/native-hana-samples.zip
```
This PR neither touches the markdown nor the source configuration for that file... 🤷🏻‍♀️

2024-04-07 17:38 UTC, mnkiefer commented
@chgeo: Could you please investigate/comment on the open fixes? Thanks! 🙏

2024-04-07 17:41 UTC, mnkiefer commented
@swaldmann: The **Lint** workflow fails with `Error: There is no diff for file`... Is this expected behavior?

2024-04-07 17:43 UTC, mnkiefer commented
@BraunMatthias: Could you please have a look at the descriptions/new examples based on our common sample for the authorization lint rules?  Your input/feedback would be very helpful and will be greatly appreciated! 😇

2024-04-08 06:54 UTC, bugwelle requested changes

2024-04-08 06:54 UTC, bugwelle commented on .npmrc
> +@sap:registry=https://registry.npmjs.org/
```suggestion
@sap:registry=https://registry.npmjs.org/

```

trailing newlines. :)

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/RulesRefTable.vue
> +        <tr v-for="entry in data[category]">
Should there be a heading for the table?

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/RulesRefTable.vue
> +    line-height: 120% !important;
Is enforcement via `!important` necessary here?

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/RulesRefTable.vue
> +    font-size: small;
Do we have a central style-guide? If so, are font sizes specified there?

2024-04-08 06:54 UTC, bugwelle commented on about/features.md
> +| [CDS Linter](../tools/cds-lint)                                                                                  | <X/> |
```suggestion
| [CDS Linter](../tools/cds-lint)                                                                                   | <X/> |
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +// This script creates a Markdown document from the CDs Lint Rules Reference.
```suggestion
// This script creates a Markdown document from the CDS Lint Rules Reference.
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +    let result = `Below you can find all rules in the \`@sap/eslint-plugin-cds\` ESLint plugin.
```suggestion
    let result = `Below you can find all rules of the \`@sap/eslint-plugin-cds\` ESLint plugin.
```

Is it `in` or `of`? (I'm not sure here)

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +They are grouped by the categories [Model Validation](#model-validation) and [Environment](#environment) to help you understand their purpose.
```suggestion
They are grouped by categories [Model Validation](#model-validation) and [Environment](#environment) to help you understand their purpose.
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +Note, that while all recommended (&nbsp;✅&nbsp;) model rules run with the CLI. However, only a number of them are
```suggestion
Note, that while all recommended (&nbsp;✅&nbsp;) model rules run with the CLI, only a number of them are
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +* *In Editor* rules: Rules that are enabled in the editor by default only rely the current file as their rule context. These are quick to execute and
```suggestion
* *In Editor* rules: Rules that are enabled in the editor by default only rely on the current file as their rule context. These are quick to execute and
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +> 🔧 &nbsp; **Fixable**: If problems reported by the rule are automatically fixable (--fix)<br>
```suggestion
> 🔧 &nbsp; **Fixable**: If problems reported by the rule are automatically fixable (\`--fix\`)<br>
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +> 👀 &nbsp; **In Editor**: If the rule is shown in the VS Code editor and rerun on file changes
This looks like it should be a list (without bullet points), just for accessibility's sake. :)
e.g. https://css.maxdesign.com.au/listutorial/02.htm

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +These are only run via the command line and are not available in the editor as they often cannot be
IIRC, our documentation uses `can't` instead of `cannot`.

```suggestion
These are only run via the command line and are not available in the editor as they often can't be
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +> 🔧 &nbsp; **Fixable**: If problems reported by the rule are automatically fixable (--fix)<br>
```suggestion
> 🔧 &nbsp; **Fixable**: If problems reported by the rule are automatically fixable (\`--fix\`)<br>
```

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +    return `::: danger No content here
Shouldn't we abort the process? Otherwise I fear that we may accidentally break our deployment in the future without noticing.

2024-04-08 06:54 UTC, bugwelle commented on tools/[rules].paths.ts
> +The CI does that in production.`
Maybe abort if some environment variable is set? i.e. look for CI?

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +const configFileName = ".eslintrc.json";
Why not the new format? `eslint.config.js`?

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +        "@sap/cds": "^7.0.0",
Can we (/you) put this into a custom `package.json`? Then the renovate bot/dependabot will pick it up and update it automatically.

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +      sources[`${file}`] = data[`${name}/${kind}/${file}`];
```suggestion
      sources[file] = data[`${name}/${kind}/${file}`];
```

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +    for (const file of files || []) {
```suggestion
    for (const file of files) {
```
you already check for truthiness in line 68.

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +// The following functions used in the above playground source code. We use them to compress
```suggestion
// The following functions are used in the above playground source code. We use them to compress
```

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +// --- Start logic from https://github.com/ota-meshi/eslint-online-playground ---
Were these snippets copy&pasted? :)
Seems like it: https://github.com/ota-meshi/eslint-online-playground/blob/e06ffb61b2654fbba61fe338c2cb8906fd30c196/src/utils/compress.ts#L23


If so, then we need to add a note to their license: https://github.com/ota-meshi/eslint-online-playground/blob/e06ffb61b2654fbba61fe338c2cb8906fd30c196/LICENSE

2024-04-08 06:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +  transform: translateX(-1rem) translateY(-3.5rem);
As I don't have a (live) preview[^1], I have to guess how it looks like. So just a question: Did you test it with different font sizes? After all, the line-height is in pixel, but you're using rem here. So with increased font size, it may not look like we expect it to. :)

[^1 ]: Didn't test it locally, yet.

2024-04-08 06:54 UTC, bugwelle commented on tools/cds-lint.md
> +  .cols-2 {
This is quite the generic class name. Are you sure this isn't used elsewhere? I'd favor a more specific class name here.

2024-04-08 06:54 UTC, bugwelle commented on tools/cds-lint.md
> +<style lang="scss" scoped>
Does CAPire use SCSS? Is it necessary for this small snippet? :)

2024-04-08 06:54 UTC, bugwelle commented on tools/cds-lint.md
> +cds lint .
Users not familiar with CLIs may wonder: Is this `.` necessary? Maybe use something like:

```suggestion
# cds lint <folder>
cds lint .
```

2024-04-08 06:54 UTC, bugwelle commented on tools/cds-lint.md
> +### CDS Lint Customization  {#cds-lint-customization}
Why is this commented out?

2024-04-08 06:54 UTC, bugwelle commented on tools/cds-lint.md
> +The following command automatically adds the settings for the ESLint VS Code extension to the project's VS Code settings, installs the CDS ESLint plugin, and adds it to the ESLint configuration of yo
```suggestion
The following command automatically adds settings for the ESLint VS Code extension to the project's VS Code settings, installs the CDS ESLint plugin, and adds it to the ESLint configuration of your project:
```

2024-04-08 06:54 UTC, bugwelle commented on tools/cds-lint.md
> +1. Download the [VS Code ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for _Visual Studio Code_. CDS Lint seamlessly integrates with it. For _SAP Busin
```suggestion
1. Download the [VS Code ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for _Visual Studio Code_. CDS Lint seamlessly integrates with it. For _SAP Business Application Studio_ this comes preinstalled.
```

Not sure, though. I've heard "comes preinstalled" more often than "is preinstalled" in this context.

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/examples/assoc2many-ambiguous-key/correct/db/schema.cds
> +  @mandatory name   : String(111);
```suggestion
  @mandatory name : String(111);
```

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/examples/assoc2many-ambiguous-key/correct/db/schema.cds
> +namespace sap.capire.bookshop;
Are all of these examples auto-generated / copied from the cds-lint source or did you add them / write them manually?

2024-04-08 06:54 UTC, bugwelle commented on tools/rules.data.ts
> +process.env.SILENT = 'true'
Why silent? I see this very often in CAP and it has hidden errors quite a few times for me.

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/start-entities-uppercase.md
> +.vp-code {
This isn't used in this files directly? Could you move it to a central place and avoid duplication?

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/no-dollar-prefixed-names.md
> +In the next example, the element `$pages` start with `$` and so the rule will raise an error for this element:
```suggestion
In the next example, the element `$pages` starts with `$` and so the rule will raise an error for this element:
```

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/no-db-keywords.md
> +But in general reserved words cannot be used as identifiers and this rule will warn you if use any of the [reserved SQL keywords](https://www.sqlite.org/lang_keywords.html).
```suggestion
But in general reserved words can't be used as identifiers and this rule will warn you if use any of the [reserved SQL keywords](https://www.sqlite.org/lang_keywords.html).
```

@renejeglinsky Or am I mistaken that CAPire uses `can't` instead of `cannot`?

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/latest-cds-version.md
> +# latest-cds-version
I didn't know if this rule. It seems this is the only rule that may break CIs any time. Shouldn't rules be deterministic/stable?

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/auth-valid-restrict-grant.md
> +The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such a
```suggestion
The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such as `READ`, `CREATE`, `UPDATE`, and `DELETE`) on entities. It also reports a warning if all standard CDS events with write semantics (`CREATE`, `DELETE`, `UPDATE`, `UPSERT`) and `*` is a wildcard for all events are used to use the virutal event `WRITE` instead.
```

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/auth-valid-restrict-grant.md
> +The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such a
Could you re-phrase the last sentence? I'm not sure what it is supposed to tell me.

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/auth-restrict-grant-service.md
> +Let's consider the following example with the `CatalogService` where there function `getViewsCount()` is restricted to the *Admin* role, granting all CDS events:
```suggestion
Let's consider the following example with the `CatalogService` where the function `getViewsCount()` is restricted to the *Admin* role, granting all CDS events:
```

2024-04-08 06:54 UTC, bugwelle commented on tools/lint/meta/auth-restrict-grant-service.md
> +An unsupported privilege is that for bound or unbound actions, the `grant` property is implicitly removed (assuming grant: '*' instead). The same also holds for functions. This rule ensures that `@re
"is that" sound like German. Could you rephrase it?

2024-04-08 07:51 UTC, mnkiefer commented on tools/lint/meta/auth-valid-restrict-grant.md
> +The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such a
I added a better explanation. Basically:
- If values do not contain 'READ, WRITE, *' (i.e. only events with write semantics are used), 'WRITE' is enough
- If values contain '*', '*' is enough

2024-04-08 07:55 UTC, mnkiefer commented on tools/lint/meta/auth-restrict-grant-service.md
> +An unsupported privilege is that for bound or unbound actions, the `grant` property is implicitly removed (assuming grant: '*' instead). The same also holds for functions. This rule ensures that `@re
You are right, I just updated it to be phrased identically to the *Authorization* docs.

2024-04-08 07:57 UTC, mnkiefer commented on tools/lint/meta/no-db-keywords.md
> +But in general reserved words cannot be used as identifiers and this rule will warn you if use any of the [reserved SQL keywords](https://www.sqlite.org/lang_keywords.html).
Got this from [here](https://cap.cloud.sap/docs/guides/databases#reserved-words).

2024-04-08 08:09 UTC, mnkiefer commented on tools/lint/meta/latest-cds-version.md
> +# latest-cds-version
Not sure what you mean, could you please elaborate/how would this break CIs so I can address your concerns? 😇

2024-04-08 08:15 UTC, mnkiefer commented on .vitepress/theme/components/RulesRefTable.vue
> +        <tr v-for="entry in data[category]">
No, we would like to keep this similar to the way [ESLint displays their rules reference](https://eslint.org/docs/latest/rules/).

2024-04-08 08:22 UTC, mnkiefer commented on .vitepress/theme/components/RulesRefTable.vue
> +    line-height: 120% !important;
Not necessary 👍

2024-04-08 08:22 UTC, mnkiefer commented on .vitepress/theme/components/RulesRefTable.vue
> +    font-size: small;
We do, but this is something specific to only that page.

2024-04-08 08:24 UTC, mnkiefer commented on tools/[rules].paths.ts
> +    let result = `Below you can find all rules in the \`@sap/eslint-plugin-cds\` ESLint plugin.
Or `from`...? 🧐

2024-04-08 08:29 UTC, mnkiefer commented on .vitepress/theme/components/PlaygroundBadge.vue
> +const configFileName = ".eslintrc.json";
This will come in the next iteration (another PR). I would prefer to keep those updates (and all other changes coming with `eslint@v9`) separate. 🤓

2024-04-08 08:34 UTC, mnkiefer commented on tools/cds-lint.md
> +### CDS Lint Customization  {#cds-lint-customization}
This is still WIP (will come with another PR).

2024-04-08 08:35 UTC, mnkiefer commented on tools/cds-lint.md
> +1. Download the [VS Code ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for _Visual Studio Code_. CDS Lint seamlessly integrates with it. For _SAP Busin
@chgeo: What do you think?

2024-04-08 08:38 UTC, mnkiefer commented on tools/lint/examples/assoc2many-ambiguous-key/correct/db/schema.cds
> +namespace sap.capire.bookshop;
There are added manually. We no longer use the examples (from our unit/integration tests) from the plugin source, but rather want Capire to have their own, and to keep them uniform in context (i.e. try to find an example based on schema/services from `cds add sample`).

2024-04-08 08:39 UTC, mnkiefer commented on tools/rules.data.ts
> +process.env.SILENT = 'true'
@chgeo: Can you comment on this?

2024-04-08 08:49 UTC, bugwelle commented on tools/lint/meta/latest-cds-version.md
> +# latest-cds-version
Once a new version arises, CI checks on pull requests and branches will fail.  While it's good to be notified of new versions (e.g. Renovate, Dependabot), it would be very annoying to have your PR checks fail for unrelated versions. 

Or your pipeline is green, push a formatting change and the checks fail. And you have no way of fixing it.

non-deterministic/unstable in the sense that if you run ESLint in your CI, using the same input files, it may fail depending on the day it is executed.

At least that's how understand this rule. I may be mistaken.

Also, just personal opinion. :)

2024-04-08 08:52 UTC, bugwelle commented on .vitepress/theme/components/RulesRefTable.vue
> +        <tr v-for="entry in data[category]">
But ESLint uses aria attributes and CSS styles to hide their headers. They use some markers and it would be great to have the same here (for accessibility: text-to-speach plugins, etc.) :)

2024-04-08 08:53 UTC, bugwelle commented on .vitepress/theme/components/RulesRefTable.vue
> +    font-size: small;
Ok. `.text-desc` is quite generic. What are the chances of collsion?

2024-04-08 08:54 UTC, bugwelle commented on .vitepress/theme/components/PlaygroundBadge.vue
> +const configFileName = ".eslintrc.json";
:+1:

2024-04-08 08:55 UTC, bugwelle commented on tools/cds-lint.md
> +### CDS Lint Customization  {#cds-lint-customization}
:+1:

2024-04-08 08:57 UTC, bugwelle commented on tools/lint/meta/auth-valid-restrict-grant.md
> +The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such a
Thanks. :)

2024-04-08 09:44 UTC, swaldmann commented on tools/cds-lint.md
> +<style lang="scss" scoped>
Yes, we're using SCSS in various places. As we're using it anyway why not also here?

2024-04-08 09:44 UTC, swaldmann commented on tools/cds-lint.md
> +  .cols-2 {
`cols-2` is used in various places for the same use case, e.g. here:
https://github.com/cap-js/docs/blob/main/about/index.md?plain=1#L7

I'd argue we should make this a global style though, irrespective of the usage here.

2024-04-08 09:44 UTC, swaldmann commented on tools/cds-lint.md
> +For all other projects of if you would like to have ESLint running within your VS Code editor, please run the dedicated [`cds add` commmand](#cds-add-lint) command to configure them.
```suggestion
For all other projects, you would like to have ESLint running within your VS Code editor. Run the dedicated [`cds add` commmand](#cds-add-lint) command to configure them.
```

2024-04-08 09:44 UTC, swaldmann commented on tools/cds-lint.md
> +DEBUG="lint" cds lint .
Can't speak for Windows, but you shouldn't need the `"` here:
```suggestion
DEBUG=lint cds lint .
```

2024-04-08 09:44 UTC, swaldmann commented on tools/cds-lint.md
> +1. Download the [VS Code ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for _Visual Studio Code_. CDS Lint seamlessly integrates with it. For _SAP Busin
Also to avoid repeating "VS Code" a bit:
```suggestion
1. Download the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for _Visual Studio Code_. CDS Lint seamlessly integrates with it. For _SAP Business Application Studio_ this comes preinstalled.
```

2024-04-08 09:59 UTC, bugwelle commented on tools/cds-lint.md
> +  .cols-2 {
:+1: for global style

2024-04-08 11:48 UTC, mnkiefer commented on .vitepress/theme/components/RulesRefTable.vue
> +        <tr v-for="entry in data[category]">
Oh, I see! 👀 I've added the headers now and decided to keep them visible as it makes everything easier to interpret.

2024-04-08 14:14 UTC, mnkiefer commented on .vitepress/theme/components/RulesRefTable.vue
> +    font-size: small;
Changed this to `.lint-rule-desc` and also adjusted other class names accordingly. 👍

2024-04-08 14:40 UTC, mnkiefer commented on tools/[rules].paths.ts
> +> 👀 &nbsp; **In Editor**: If the rule is shown in the VS Code editor and rerun on file changes
Done 👍

2024-04-08 14:47 UTC, mnkiefer commented on tools/[rules].paths.ts
> +    return `::: danger No content here
I agree, it should always throw except for the `MODULE_NOT_FOUND` case. I adapted it accordingly. 👍

2024-04-08 14:48 UTC, mnkiefer commented on tools/[rules].paths.ts
> +The CI does that in production.`
Done. See my reply to your previous comment.

2024-04-08 15:01 UTC, mnkiefer commented on .vitepress/theme/components/PlaygroundBadge.vue
> +        "@sap/cds": "^7.0.0",
Great idea! 💡 I just added a _package.json_ file explicitly.

2024-04-08 16:21 UTC, mnkiefer commented on .vitepress/theme/components/PlaygroundBadge.vue
> +  transform: translateX(-1rem) translateY(-3.5rem);
I agree, this is better to do in px. I just updated this. 👍

2024-04-08 16:34 UTC, mnkiefer commented on tools/cds-lint.md
> +cds lint .
We can just use `cds lint` here. The `.` is the default expression.

2024-04-08 16:35 UTC, mnkiefer commented on tools/rules.data.ts
> +process.env.SILENT = 'true'
Not needed here 👍

2024-04-08 16:40 UTC, mnkiefer commented on tools/lint/meta/start-entities-uppercase.md
> +.vp-code {
You are right, this can be moved into _PlaygroundBadge.vue_.

2024-04-10 10:50 UTC, mnkiefer commented
@bugwelle, @chgeo: Are you ok with merging this and we take up the TODOS (see above) in follow-up PRs?

2024-04-10 12:27 UTC, chgeo approved these changes
+1 for doing follow-up work in separate PRs

2024-04-10 15:14 UTC, chgeo commented
@swaldmann there is an error from the md linter: `Error: There is no diff for file ./tools/lint/meta/extension-restrictions.md.`  Any idea what's wrong there?

2024-04-10 16:18 UTC, swaldmann commented
I changed the error message to also tell us which diffs were found and it seems the review creator can't deal with newly added subfolders. For this PR you can ignore it, I'll check when I have time.

2024-04-10 18:24 UTC, renejeglinsky commented on tools/lint/meta/assoc2many-ambiguous-key.md
> +### Examples
I'd vote for making this a L2 header, as well as for the Version section. Right now, the "On this page" menu looks odd as it only shows L2 headers:
![image](https://github.com/cap-js/docs/assets/32062331/911a9c8a-5781-49c9-af69-c6ddc85db3af)
Applies to all rules.

2024-04-10 18:42 UTC, renejeglinsky commented on tools/lint/meta/auth-restrict-grant-service.md
> +Restrictions can be defined on different types of CDS resources, but there are some limitations with regards to supported privileges (see [limitations](../../../guides/security/authorization#supporte
This sentence starts the next paragraph.
```suggestion
Restrictions can be defined on different types of CDS resources, but there are some limitations with regards to supported privileges (see [limitations](../../../guides/security/authorization#supported-combinations-with-cds-resources)).
```

2024-04-10 18:44 UTC, renejeglinsky commented on tools/lint/meta/auth-restrict-grant-service.md
> +Unsupported privilege properties are ignored by the runtime. Especially, for bound or unbound actions, the `grant` property is implicitly removed (assuming grant: '*' instead). The same also holds fo
```suggestion
Unsupported privilege properties are ignored by the runtime. Especially, for bound or unbound actions, the `grant` property is implicitly removed (assuming `grant: '*'` instead). The same is true for functions. This rule ensures that `@restrict.grant` on service level and for bound/unbound actions and functions is limited to `grant: '*'`.
```

2024-04-10 18:49 UTC, renejeglinsky commented on tools/lint/meta/auth-valid-restrict-grant.md
> +The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such a
```suggestion
The `grant` property of a `@restrict` privilege defines one or more events that the privilege applies. This rule checks for valid values of `@restrict.grant`, that is, all standard CDS events (such as `READ`, `CREATE`, `UPDATE`, and `DELETE`) on entities. It also suggests to use `*` only when listing events including `*` and to use `WRITE` only when using solely standard CDS events with write semantics (`CREATE`, `DELETE`, `UPDATE`, `UPSERT`).
```

2024-04-10 18:50 UTC, renejeglinsky commented on tools/lint/meta/auth-valid-restrict-grant.md
> +In the next example, the `@restrict.grant` has a typo in the event (i.e. `REAAD`instead of `READ`) for the `Viewer` role, which is not a valid value for `@restrict.grant` so the rule will report a wa
```suggestion
In the next example, the `@restrict.grant` has a typo in the event (that is, `REAAD` instead of `READ`) for the `Viewer` role, which is not a valid value for `@restrict.grant` so the rule will report a warning:
```

2024-04-10 18:55 UTC, renejeglinsky commented on tools/lint/meta/auth-valid-restrict-keys.md
> +In the following example, the `@restrict` annotation on `CatalogService.ListOfBooks` has correctly spelled keys `to`, `grant`, and `where` keys in the defined privilege:
```suggestion
In the following example, the `@restrict` annotation on `CatalogService.ListOfBooks` has correctly spelled `to`, `grant`, and `where` keys in the defined privilege:
```

2024-04-11 04:55 UTC, renejeglinsky commented on tools/lint/examples/auth-valid-restrict-where/incorrect/srv/cat-service.cds
> +  @(restrict: [{ grant: 'READ', to: '', where: 'CreatedBy === $user' }])
```suggestion
  @(restrict: [{ grant: 'READ', to: 'Viewer', where: 'CreatedBy === $user' }])
```

2024-04-11 05:46 UTC, renejeglinsky commented on tools/lint/examples/sql-cast-suggestion/incorrect/db/schema.cds
> +    title || name as name1 : String,
There's no `name2`. Maybe this should be name2?
```suggestion
    title || name as name2 : String,
```
![image](https://github.com/cap-js/docs/assets/32062331/b05e52ce-b257-4f5f-8baf-0fbaa2fc2dce)

2024-04-11 05:58 UTC, renejeglinsky commented on tools/lint/meta/assoc2many-ambiguous-key.md
> +### Examples
I can also make this change if it's agreed :)

2024-04-11 06:31 UTC, mnkiefer commented on tools/lint/meta/assoc2many-ambiguous-key.md
> +### Examples
Nice! And no worries, it's already in. 👍

2024-04-11 06:35 UTC, mnkiefer commented on tools/lint/examples/auth-valid-restrict-where/incorrect/srv/cat-service.cds
> +  @(restrict: [{ grant: 'READ', to: '', where: 'CreatedBy === $user' }])
Good catch! 🚀

2024-04-11 10:23 UTC, renejeglinsky commented on .vitepress/theme/components/RulesRefTable.vue
> +            <li>🔧 &nbsp; <b>Fixable</b>: If problems reported by the rule are automatically fixable (\`--fix\`)</li>
The `--fix` option is not displayed properly:
![image](https://github.com/cap-js/docs/assets/32062331/36a668b6-98d6-4882-8267-bc89016f9746)

2024-04-11 10:23 UTC, renejeglinsky commented on .vitepress/theme/components/RulesRefTable.vue
> +            <li v-if="category !== 'Environment'">👀 &nbsp; <b>In Editor</b>: If the rule is shown in the VS Code editor and rerun on file changes</li>
```suggestion
            <li v-if="category !== 'Environment'">👀 &nbsp; <b>In Editor</b>: If the rule is shown in the VS Code editor and re-run on file changes</li>
```

2024-04-11 11:51 UTC, renejeglinsky approved these changes

2024-04-11 12:18 UTC, merged