WIP: .hdbcds to .hdbtable migration guide
cap-js/docs pull request #825
Opened 2024-04-12 08:52 UTC by simonoswald

2024-06-19 04:58 UTC, renejeglinsky commented
We can and should start to merge all PRs related to the next major. I think this is an important PR that everyone should pick up again.
@simonoswald @stewsk @patricebender

2024-06-25 14:36 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +which would causes a full table migration.
For me this implied that `HDBCDS` files also have `WITH ASSOCIATIONS`.

They come with "Associations" but as part of the column definitions.

2024-06-25 14:36 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +native associations without a full table migration.
```suggestion
Then run a new build and deploy the newly generated `.hdbcds` files.
The resulting database tables and views shouldn't contain any `associations` anymore.
In contrast to the hdbtable plugin, the hdbcds plugin is able to handle removal of the
native associations without a full table migration.
```

2024-06-25 14:36 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +__before__ the actual hdbcds to hdbtable migration.
```suggestion
The CAP Java runtime and the CAP Nodejs runtime with the new SAP HANA service (`@cap-js/hana`, default in CDS 8)
don't need the `WITH ASSOCIATIONS` clause any more. The workaround is to remove the `associations` from the `hdbcds` sources
__before__ the actual `hdbcds` to `hdbtable` migration.
```

2024-06-25 14:36 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +First switch of the generation of the `WITH ASSOCIATIONS` clause (both for hdbcds and hdbtable):
```suggestion
First switch of the generation of the `associations` (that option accounts for "associations" in the `hdbcds` sources as well as for the `WITH ASSOCIATIONS` found in the `hdbtable` sources):
```

2024-06-26 10:44 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +which would causes a full table migration.
hi @patricebender , I have rephrased the section on associations. Is it clearer now?

2024-06-26 11:28 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +These clauses slightly differ, which causes a full table migration when switching from hdbcds to hdbtable.
🥇

2024-06-26 11:30 UTC, patricebender reviewed
The `WITH ASSOCIATIONS` part of the guide now looks good to me.
I think the `multiline comments` part needs some clarifications, though.

2024-06-26 11:35 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +First disable the doc comments by setting option `hana.comments` to `false`.
done

2024-06-26 11:47 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +`COMMENT`s without a full table migration.
@patricebender  have changed it, please check

2024-06-26 12:18 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +`COMMENT`s without a full table migration.
bueno

2024-06-26 12:34 UTC, patricebender approved these changes

2024-06-26 12:44 UTC, stewsk approved these changes

2024-06-27 08:12 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +Not relevant for SAP HANA Cloud.
```suggestion
If you are using SAP HANA Cloud, you don't have to do anything, as there is no HANA CDS on SAP HANA Cloud.
```

An explaining sentence on why its not relevant maybe?

2024-06-27 08:13 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +with the following 4 steps. This guide assumes you use @sap/cds@7 or higher.
@patricebender if I understood you correctly we need cds@8 to do the no-assoc-step, right?

2024-06-27 08:14 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +Info: The deploy format determines only the "medium" how your database model is brought to the database.
TODO: Real info-box?

2024-06-27 08:18 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +The CAP Java runtime and the CAP Nodejs runtime with the new SAP HANA service (`@cap-js/hana`, default in CDS 8)
```suggestion
The CAP Java runtime and the CAP Nodejs runtime with the new SAP HANA service (`@cap-js/hana`, default in @sap/cds@8)
```

2024-06-27 08:19 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +* CAP CDS 8,
```suggestion
* @sap/cds@8,
```

2024-06-27 08:20 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +Note: If you need the comments in the database, this workaround will not help,
TODO: Do as warning block?

2024-06-27 08:31 UTC, patricebender commented on cds/compiler-hdbcds-to-hdbtable.md
> +with the following 4 steps. This guide assumes you use @sap/cds@7 or higher.
yes because when I tested it with 7.9.2, the `"native_hana_associations": false` was not doing anything

2024-06-28 07:04 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +  This document describes the migration from .hdbcds-based HDI deployment to .hdbtable-based HDI deployment.
AI-generated short description.
```suggestion
The deploy format `hdbcds` for SAP HANA has been deprecated with @sap/cds-compiler@5 and @sap/cds@8, and users are advised to switch to the default format `hdbtable`. This guide provides a step-by-step process for making the switch, including potential issues and workarounds, such as handling annotations `@sql.append` or `sql.prepend`, dealing with associations, multiline doc comments, and temporal data with time slice IDs.
```

2024-06-28 09:19 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +Info: The deploy format determines only the "medium" how your database model is brought to the database.
done

2024-06-28 09:23 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +Note: If you need the comments in the database, this workaround will not help,
done

2024-06-28 09:30 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +::: warning Requirements
@renejeglinsky I don't get this comment - what is wrong with the original line, it does specify a container type "warning" ?

2024-06-28 09:35 UTC, stewsk commented
Hi @renejeglinsky , from our point of view this guide now is ok.
Providing this guide is the TODO mentioned in the Release Notes/Compiler/Miscellaneous/hdbcds is deprecated.
Once available, it should be linked there.

Open question: where to put this guid. I would think it best fits to Cookbook Databases. Maybe don't show it in the navigation tree but make it reachable only via links?

2024-06-28 13:03 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +::: warning Requirements
I guess this was a mistake. We can ignore it.

2024-06-28 13:04 UTC, renejeglinsky commented
> Hi @renejeglinsky , from our point of view this guide now is ok. Providing this guide is the TODO mentioned in the Release Notes/Compiler/Miscellaneous/hdbcds is deprecated. Once available, it should be linked there.
> 
> Open question: where to put this guid. I would think it best fits to Cookbook Databases. Maybe don't show it in the navigation tree but make it reachable only via links?

So linking it from the HANA DB Guide, right? Then I'd propose to have an intro section in that guide and link the guide from there.

2024-06-28 13:50 UTC, stewsk commented
> Then I'd propose to have an intro section in that guide and link the guide from there.

Stupid thing is that the HANA DB Guide is title "SAP HANA Cloud", for which the migration guide is not relevant ... 
And we should make the section that links to the migration guide not too prominent, as most people should already be on HANA Cloud.

2024-07-05 11:45 UTC, smahati requested changes

2024-07-08 06:34 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +   <!-- **TBD** must it be exactly the same? Does it also work if the current model
I cannot answer this with confidence, no. I think we should have "Ensure your current data model matches the deployed data model." as a hard requirement!

2024-07-08 06:41 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +    <!-- **TODO** Without this entry, during HDI deployment you will get errors like ... -->
We would get errors like this:

```
    Error: "db://E": the object cannot be provided more than once [8212002]
     "src/E.hdbtable": the file would provide it 
     "$cds.merge/E": the deployed file already provides it 
      Merged from "src/E.hdbcds"
```

2024-07-08 06:41 UTC, simonoswald commented on cds/compiler-hdbcds-to-hdbtable.md
> +    <!-- **TODO** Without this entry, during HDI deployment you will get errors like ... -->
Maybe put this in an info-box? warning-box?

2024-07-08 09:56 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +   <!-- **TBD** must it be exactly the same? Does it also work if the current model
Ok, then we keep the text as is, I will remove the TBD comment

2024-07-08 11:31 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +    <!-- **TODO** Without this entry, during HDI deployment you will get errors like ... -->
Have added the error message.
I leave it to @smahati and @renejeglinsky whtherthey want to have it in a box or not ...

2024-07-12 07:12 UTC, renejeglinsky commented
> Stupid thing is that the HANA DB Guide is title "SAP HANA Cloud", for which the migration guide is not relevant ... And we should make the section that links to the migration guide not too prominent, as most people should already be on HANA Cloud.

Linking it from the "Common" Guide also feels odd for me. Maybe adding a note or sth alike in this section? https://pages.github.tools.sap/cap/docs/guides/databases-hana#deploy-artifact-transitions 

Even though it is the HANA Cloud guide it probably is a good fit?

2024-07-12 07:44 UTC, stewsk commented
@renejeglinsky 
> Linking it from the "Common" Guide also feels odd for me. Maybe adding a note or sth alike in this section? https://pages.github.tools.sap/cap/docs/guides/databases-hana#deploy-artifact-transitions

>Even though it is the HANA Cloud guide it probably is a good fit?

Yes, you're right, that is a good spot.

2024-07-12 08:13 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +redirect_from: releases/compiler-v2
This redirect is not needed, right? It also doesn't work:
![image](https://github.com/user-attachments/assets/5446f38c-6759-44b6-ae01-6d81b40f753a)

2024-07-12 08:14 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +#status: internal
I guess it should be release, right? ;)
```suggestion
status: released
```

2024-07-12 08:16 UTC, stewsk commented on cds/compiler-hdbcds-to-hdbtable.md
> +redirect_from: releases/compiler-v2
Yes. I guess that was a copy and past thing in the initial version of this guide. Just remove it.

2024-07-12 08:18 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +    <!-- **TODO** Without this entry, during HDI deployment you will get errors like ... -->
Added it to a detail box.

2024-07-12 08:19 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +    ```
```suggestion
    ```log
```

2024-07-12 08:21 UTC, renejeglinsky commented on cds/compiler-hdbcds-to-hdbtable.md
> +redirect_from: releases/compiler-v2
Done

2024-07-12 08:21 UTC, renejeglinsky approved these changes

2024-07-12 08:36 UTC, merged

2024-07-12 08:45 UTC, stewsk commented
@renejeglinsky  machst du auch noch den Link auf das Dokument in den Release Notes /da ist noch ein TODO), oder soll ich?

2024-07-12 08:50 UTC, renejeglinsky commented
> @renejeglinsky machst du auch noch den Link auf das Dokument in den Release Notes (da ist noch ein TODO), oder soll ich?

Hatte ich schon vorbereitet und jetzt gepusht. Danke!