Badge for required versions
cap-js/docs pull request #844
Opened 2024-04-17 14:03 UTC by chgeo

Looks like
![image](https://github.com/cap-js/docs/assets/7470719/56b905e3-0864-41c7-8224-62f53ac7c62e)

2024-04-17 14:09 UTC, chgeo commented
@LotharBender FYI

2024-04-17 14:46 UTC, chgeo commented on about/index.md
> +- <Since version="1.2.3" of="@sap/..." /> — The marked feature is only available with the given version or higher.
@renejeglinsky @smahati Please check on the texts here + the `title` texts in the `.vue` files.

2024-04-17 18:23 UTC, renejeglinsky commented on about/index.md
> +- <Since version="1.2.3" of="@sap/..." /> — The marked feature is only available with the given version or higher.
_Since_ would just be usable for things that have already been delivered. If we'd want to have a mechanism to say that this doc is only valid from an upcoming version going forward, we'd need to do sth different. But maybe both is an edge case and the "future" badge is even less often I'd guess.
Using "as of" is defined in Merriam Webster as "used to indicate a time or date at which something begins or ends". So could fit in both scenarios.

2024-04-18 07:27 UTC, chgeo commented on about/index.md
> +- <Since version="1.2.3" of="@sap/..." /> — The marked feature is only available with the given version or higher.
I see your point with the upcoming releases, but I doubt that users would see a difference in _since_ vs. _requires_ vs. _as of_.  They would not find that version and then hopefully get the point and not create a ticket for us.

An alternative would be to specifically use a text like _as of upcoming version_, but this we would have to change again once we publish.  Too much effort imho.

But we could change it to _as of_ if you like.

2024-04-18 08:08 UTC, swaldmann approved these changes

2024-04-18 09:33 UTC, smahati commented on about/index.md
> +- <Since version="1.2.3" of="@sap/..." /> — The marked feature is only available with the given version or higher.
I like requires best because that seems to be the best one to convey the intent (it won't work without this), If we want to make it seem more like "requires at least" maybe  we can use "minimum", like "minimum @sap/cds-dk:V7.5". wdyt?

2024-04-18 13:25 UTC, smahati commented on .vitepress/theme/components/Beta.vue
> +    title="This is a beta feature. Beta features aren't part of the officially delivered scope that SAP guarantees for future releases."
```suggestion
    title="Beta features are planned to be generally available in subsequent releases, however, APIs and their behavior are not final and may change in the general release."
```
This is what we said in the glossary so maybe we can keep it the same?

2024-04-18 13:32 UTC, smahati requested changes

2024-04-18 13:32 UTC, smahati commented on .vitepress/theme/components/Alpha.vue
> +    title="This is an alpha feature. Alpha features are experimental. They may never be generally available. If released subsequently, the APIs and behavior might change."
```suggestion
    title="Alpha features are experimental. They may never be generally available. If released subsequently, the APIs and behavior might change."
```

2024-04-18 13:32 UTC, smahati commented on .vitepress/theme/components/Beta.vue
> +    title="This is a beta feature. Beta features aren't part of the officially delivered scope that SAP guarantees for future releases."
```suggestion
    title="Beta features are planned to be generally available in subsequent releases, however, APIs and their behavior are not final and may change in the general release."
```

2024-04-18 14:41 UTC, chgeo commented on about/index.md
> +- <Since version="1.2.3" of="@sap/..." /> — The marked feature is only available with the given version or higher.
I have changed it to _requires_

2024-04-18 14:45 UTC, smahati approved these changes

2024-04-18 14:56 UTC, merged