Migration Guide for CAP Java 3.0
cap-js/docs pull request #892
Opened 2024-05-02 14:56 UTC by beckermarc

Feature Branch for development of CAP Java 3.0 migration guide. This branch should be merged for the major release in July.

2024-05-13 13:49 UTC, mofterdinger commented on java/migration.md
> +### Replaced Poperties
Properties

2024-06-06 12:18 UTC, renejeglinsky commented on java/migration.md
> +This is a **preview** of the changes planned for CAP Java 3.0 (planned to be released July 2024)
```suggestion
This is a **preview** of the changes planned for CAP Java 3.0 (planned to be released June 2024)
```

2024-06-19 09:49 UTC, BraunMatthias commented
can we merge as a first draft to capire? I'd like to show in stakeholder round

2024-06-19 10:41 UTC, MattSchur commented on java/migration.md
> +| `$user.tenant` | `$tenant` | removal |
```suggestion
| `$user.tenant` | `$tenant` | `$user.tenant` is deprecated in `@restrict` and unsupported in `@cds.on.insert|update` |
```

2024-06-19 11:46 UTC, beckermarc commented on java/migration.md
> +| `$user.tenant` | `$tenant` | removal |
@MattSchur and I also had internal discussions on this, he opened a PR to support $tenant in @restrict in CDS Services

2024-06-20 12:21 UTC, MattSchur commented on java/migration.md
> +Select.from(Books_.class).columns(t -> t.expand());
```suggestion
Select.from(BOOKS).columns(b -> b.expand());
```

2024-06-20 12:23 UTC, MattSchur commented on java/migration.md
> +This does not impact the OData where the `expand=*` will be transformed to explicit association expand.
```suggestion
This does not impact OData where `expand=*` is transformed into expands for all associations.
```

2024-06-21 07:41 UTC, smahati requested changes

2024-06-21 07:43 UTC, beckermarc commented on java/migration.md
> +If you have customized the security configuration, you need to adapt it to the new library. If your application had a direct dependency to `cds-feature-xsuaa`, we recommend to adopt one of our starte
```suggestion
If you have customized the security configuration, you need to adapt it to the new library. If your application had a direct dependency to `cds-feature-xsuaa`, we recommend to adopt one of our starter bundles `cds-starter-cloudfoundry` or `cds-starter-k8s`.
```

2024-06-21 07:48 UTC, beckermarc commented on java/migration.md
> +| `sharedInterfaces` | `false` | `true` | Enables the usage of interfaces generated for the global types with inline anonymous arrayed types in the interfaces generated for actions and functions |
@vmikhailenko Can you help clarify that. To be honest I am struggling to understand the original sentence and can't really judge if the new suggestion is semantically correct.

2024-06-21 10:27 UTC, vmikhailenko commented on java/migration.md
> +| `sharedInterfaces` | `false` | `true` | Enables the usage of interfaces generated for the global types with inline anonymous arrayed types in the interfaces generated for actions and functions |
Yes, that is correct.

2024-06-21 11:29 UTC, beckermarc commented on java/migration.md
> +| `sharedInterfaces` | `false` | `true` | Enables the usage of interfaces generated for the global types with inline anonymous arrayed types in the interfaces generated for actions and functions |
But I still don't understand what it means :D What global types are you referring to? What does it mean that these interfaces are generated _with inline anonymous arrayed types_? What kind of types are we referring to here? I think to me it is not clear which types refers to a Java type and which to a CDS type.

2024-06-26 11:11 UTC, BraunMatthias commented
Can this PR be merged now? We need the links in other parts of documentation.

2024-06-26 14:08 UTC, beckermarc commented on java/migration.md
> +| `sharedInterfaces` | `false` | `true` | Interfaces are generated for the global types with inline anonymous arrayed types, `sharedInterfaces` enables their usage in the interfaces generated for act
```suggestion
| `sharedInterfaces` | `false` | `true` | Interfaces for global arrayed types with inline anonymous type are now generated exactly once. `sharedInterfaces` ensures such types are not generated as inline interfaces again, if used in events, actions or functions. |
```

2024-06-27 06:33 UTC, renejeglinsky commented on java/migration.md
> +[Learn more about the security configuration.](./security.md#configure-xsuaa-and-ias-authentication--xsuaa-ias){.learn-more}
```suggestion
[Learn more about the security configuration.](./security.md#xsuaa-ias){.learn-more}
```

2024-06-27 06:34 UTC, renejeglinsky commented on java/migration.md
> +[Learn more about the security configuration.](./security.md#xsuaa-ias){.learn-more}
```suggestion
[Learn more about the security configuration.](./security#xsuaa-ias){.learn-more}
```

2024-06-28 07:34 UTC, BraunMatthias approved these changes

2024-07-01 14:05 UTC, smahati approved these changes

2024-07-01 14:08 UTC, merged

2024-07-01 14:14 UTC, beckermarc commented on java/migration.md
> +If you are using the root path `/` for readiness or liveness probing in Kyma you will need to adjustment them, in this case
@smahati "readiness probe" and "liveness probe" are fixed terms in the Kyma/Kubernetes world: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/. I don't know if you were aware of that, but I think it might make sense to keep those terms.

2024-07-05 12:27 UTC, smahati commented on java/migration.md
> +If you are using the root path `/` for readiness or liveness probing in Kyma you will need to adjustment them, in this case
hmm yes, adding an article there would have been better, I'll write that on main.