Add description for typescript facet and build script
cap-js/docs pull request #971
Opened 2024-06-03 06:46 UTC by daogrady

1. Adds a description for how to use `cds add typescript`
2. Adds a description for using `cds build` with TypeScript (which replaces the steps that formerly had to be done manually)
3. Updates the output for `cds-typer --help`

2024-06-05 06:35 UTC, renejeglinsky commented on node.js/typescript.md
> +A dedicated build task for `cds-build` is provided as part of the `cds-typer` package. See [there](../tools/cds-typer#integrate-into-your-multitarget-application) for more information on how to custo
```suggestion
A dedicated build task for `cds-build` is provided as part of the `cds-typer` package. See [Integrate Into Your Multitarget Application](../tools/cds-typer#integrate-into-your-multitarget-application) for more information on how to customize this task.
```

2024-09-11 08:04 UTC, LotharBender requested changes

2024-09-11 08:04 UTC, LotharBender commented on node.js/typescript.md
> +A dedicated build task for `cds-build` is provided as part of the `cds-typer` package. See [Integrate Into Your Multitarget Application](../tools/cds-typer#integrate-into-your-multitarget-application
```suggestion
A dedicated build task for `cds build` is provided as part of the `cds-typer` package. See [Integrate Into Your Multitarget Application](../tools/cds-typer#integrate-into-your-multitarget-application) for more information on how to customize this task.
```

2024-09-11 08:18 UTC, LotharBender approved these changes

2024-09-11 10:17 UTC, daogrady commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project contains a `tsconfig.json`.
Not sure I understand correctly. If you are referring to the [former build task script](https://cap.cloud.sap/docs/tools/cds-typer#integrate-into-your-multitarget-application), then you are correct that it should still work. But I believe it is now completely redundant, as the automatic build task achieves the same thing.
Not sure what the overarchig CAPire-philosophy on that is, but personally, I try to refrain from promoting TIMTOWTDI whenever possible for the sake of clarity.

2024-09-16 05:39 UTC, renejeglinsky commented on node.js/typescript.md
> +2. Add a _tsconfig.json_ file to your project. A basic _tsconfig.json_ can be generated by running:
```suggestion
2. Add a basic _tsconfig.json_ file to your project:
```

2024-09-16 05:42 UTC, renejeglinsky commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project has a dependency on `typescript`.
I don't understand how this relates to MTA. Where is the connection?

2024-09-16 06:19 UTC, daogrady commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project has a dependency on `typescript`.
Sorry, maybe I misunderstood the MTA build. Doesn't `cds build` prepare all files to ultimately create a `.mtar` file, which is then used for MTA deployment?

2024-09-16 07:44 UTC, renejeglinsky commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project has a dependency on `typescript`.
Well, I'd say you're right, but MTA build is not the only way to use `cds build` so I'd expect either a different (more generic) title or a hint towards MTA deployment and maybe a link to the deploy guide.

2024-09-16 08:56 UTC, daogrady commented on tools/cds-typer.md
>  ## Integrate Into Your Multitarget Application
@renejeglinsky I see, that makes sense, sense for pointing it out! What do you think about this section title instead?
```suggestion
## Integrate Into Your Build Process
```

2024-09-16 10:29 UTC, renejeglinsky commented on tools/cds-typer.md
>  ## Integrate Into Your Multitarget Application
Sounds good to me :)

2024-09-16 10:29 UTC, renejeglinsky commented on node.js/typescript.md
> +A dedicated build task for `cds build` is provided as part of the `cds-typer` package. See [Integrate Into Your Multitarget Application](../tools/cds-typer#integrate-into-your-multitarget-application
```suggestion
A dedicated build task for `cds build` is provided as part of the `cds-typer` package. See [Integrate Into Your Multitarget Application](../tools/cds-typer#integrate-into-your-build-process) for more information on how to customize this task.
```

2024-09-16 10:31 UTC, renejeglinsky commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project has a dependency on `typescript`.
```suggestion
Having `cds-typer` present as dependency provides a build task "`typescript`". If your project, in addition, has a dependency on `typescript,` this build tasks is automatically included as part of `cds build`.
```

2024-09-17 05:35 UTC, daogrady commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project contains a `tsconfig.json`.
Is this still a blocker? Not entirely opposed to leaving it in if you prefer to. 🙂 If you have any more feedback, do let me know

2024-09-17 07:08 UTC, renejeglinsky approved these changes

2024-09-17 07:08 UTC, renejeglinsky commented on tools/cds-typer.md
> +Having `cds-typer` present as dependency provides a build task "`typescript`" which is automatically included as part of `cds build` if your project contains a `tsconfig.json`.
No not  a blocker :)

2024-09-17 07:09 UTC, merged

2024-09-17 07:50 UTC, LotharBender commented on tools/cds-typer.md
> +    "outDir": "./gen/srv",
`outDir` seems to match the default value and might not need to be explicitly configured: `path.join(cds.env.build.target, cds.env.folders.srv)`

2024-09-18 05:26 UTC, daogrady commented on tools/cds-typer.md
> +    "outDir": "./gen/srv",
🤔 I don't think we can dynamically add values here, as this is the recommendation for the basic layout of a tsconfig.json, which is a static file.

2024-09-18 09:28 UTC, LotharBender commented on tools/cds-typer.md
> +    "outDir": "./gen/srv",
I thought the `typescript` build task could calculate the default path if `outDir` isn't set. 
Of course, this is only an option if `outDir` isn't used by the typescript compiler itself which seems to be the case.